---
title: "Wk6 practical"
author: "Riko Munakata"
date: "11/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("lavaan")
library(lavaan)
```
```{r}
install.packages("semPlot")
library(semPlot)
```
```{r}
install.packages("boot")
library(boot)
```
```{r}
library(tidyverse)

```
```{r}
twisl <- read.csv("twisleton.csv")
```

```{r}
ggplot(twisl, aes(x=pa)) + geom_histogram()
```
```{r}
ggplot(twisl, aes(x=na)) + geom_histogram()
```
```{r}
ggplot(twisl, aes(x=rqual)) + geom_histogram()
```
```{r}
ggplot(twisl, aes(x=psyflx)) + geom_histogram()
```
```{r}
ggplot(twisl, aes(x=psyflx, y=rqual)) + geom_point() + geom_smooth(method=lm)
```
```{r}
twisl <- mutate(twisl, length = relleng_yrs*12+relleng_mos)
```

```{r}
ggplot(twisl, aes(x=length)) + geom_histogram() #no

```
```{r}
twisl %>% summarise(max(length)/12) #53.5yrs
```
```{r}
twisl %>% count(gender, cohabit)
```


```{r}
twisl <- twisl %>% na_if(99)
```

```{r}
twisl <- twisl %>% mutate(gender=gender %>% as.factor(),
                          cohabit=cohabit %>% as.factor())
```

```{r}
mod1_lm <- lm(rqual ~ psyflx, data=twisl)
summary(mod1_lm)
```

```{r}
Model <- '
rqual ~ psyflx
'

mod1_sem <- sem(Model, data=twisl)
summary(mod1_sem, rsquare=T)
```
```{r}
mod1_sem <- sem(rqual~psyflx, data=twisl)
```

```{r}
mod1_H1 <- sem(rqual~psyflx+pa+na+length+age+PPR+ cohabit, data=twisl)
summary(mod1_H1, rsquare=T)
```
```{r}
Model <- '
rqual ~ psyflx + pa + na + length + age + PPR + cohabit
'

mod1_H11 <- sem(Model, data=twisl)
summary(mod1_H11, rsquare=T)

```
```{r}
Model2 <- '
        pa ~ a*psyflx
        rqual ~ b*pa + c*psyflx
        
        
        indirect := (a*b)
        direct  :=  c
        total   := c + (a*b)
        '
```

```{r}
mod2 <- sem(Model2, twisl)
summary(mod2, rsquare=T)

```
```{r}
semPaths(mod2)
```
```{r}
semPaths(object = mod2, #model object
        what = 'paths', #this shows path names
         sizeMan = 10, #observed variable text size
         edge.label.cex = 1.2, #size of numbers
         edge.color = 'black', #default is green
        rotation= 2) #this moves psyflex to the left
```
```{r}
Model3 <- '
        pa ~ a*psyflx
        rqual ~ b*pa + c*psyflx+e*na
        na ~ d*psyflx
        
        indirect_pa := (a*b)
        indirect_na := (d*e)
        direct  :=  c
        total   := c + (a*b)+(d*e)
        '
mod3 <- sem(Model3, twisl)
summary(mod3, rsquare=T)
```
```{r}
semPaths(object = mod3, #model object
        what = 'paths', #this shows path names
         sizeMan = 10, #observed variable text size
         edge.label.cex = 1.2, #size of numbers
         edge.color = 'black', #default is green
        layout = "circle") #this moves psyflex to the left
```
```{r}
anova(mod3, mod2)
```


```{r}
Model4 <- '
        pa ~ a*psyflx + age + length + cohabit + PPR
        
        rqual ~ b*pa + c*psyflx + e*na + age + length + cohabit + PPR
        
        na ~ d*psyflx + age + length + cohabit + PPR
        psyflx ~ age + length + cohabit + PPR
        
        indirect_pa := (a*b) 
        indirect_na := (d*e)
        direct  :=  c
        total   := c + (a*b) + (d*e)
        '
mod4 <- sem(Model4, twisl)
summary(mod4, rsquare=T)

```
```{r}
path_bc <- lm(rqual ~ pa + psyflx, data=twisl)
summary(path_bc)
```
```{r}
#path b estimate: 0.31187   SE: 0.03512 
b <-0.31187 
b_se <-0.03512 

#path c estimate: 0.34366  SE:  0.03388 
c <-0.34366
c_se <- 0.03388 
```

```{r}
path_a <- lm(pa ~ psyflx, data=twisl)
summary(path_a)
```
```{r}
#path a estimate: 0.31640  SE:  0.02661 
a <-0.31640
a_se <-0.02661

```

```{r}
indirect <- a*b
#0.09867567
```

```{r}
total <- c + a*b
#0.4423357
```

```{r}
ab_function1 <- function(data, indices) {
  d <- data[indices,]
  model1 <- lm(rqual ~ pa + psyflx, data=d) #y~m+x
  model2 <- lm(pa ~ psyflx, data=d) #m~x
  return(coef(model1)[2]*coef(model2)[2]) #calculate indirect effect a*b the 2nd coefficent in each model output, in the 2nd column
}
```

```{r}
set.seed(5) #set random seed to always get the same set of bootstrapped samples
ab_boot1 <- boot(data = twisl, statistic = ab_function1, R = 5000)
```

```{r}
ab_boot1
```

```{r}
plot(ab_boot1)
```
```{r}
boot.ci(ab_boot1)
```
```{r}

```

